# Generated by Django 4.1.1 on 2023-02-14 04:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="1", editable=False, populate_from="title"
            ),
        ),
    ]
