# Generated by Django 4.1.1 on 2023-02-14 04:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="title", editable=False, populate_from="title"
            ),
        ),
    ]
