# Generated by Django 4.1.1 on 2023-02-14 04:55

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=models.CharField(max_length=100),
                editable=False,
                populate_from="title",
            ),
        ),
    ]
