# Generated by Django 4.1.1 on 2023-02-14 05:02

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from=models.CharField(max_length=100)
            ),
        ),
    ]
