# Generated by Django 4.1.1 on 2023-02-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=100, verbose_name="First name"),
        ),
    ]
