# Generated by Django 4.1.1 on 2023-02-14 05:13

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
        migrations.AlterField(
            model_name="blog", name="title", field=models.CharField(max_length=100),
        ),
    ]
